'use client';
import { useEffect, useRef, useState, useCallback, type CSSProperties } from 'react';
import { Compass, Crosshair, Backpack, CircleHelp, Volume2, VolumeX, Settings2, ArrowUpRight, ArrowRight, ArrowLeft, ChevronRight, ChevronLeft, Sparkles, Swords, Target, Users, Wind, Coins, Star, Heart, Shield, Flame, Zap, Check, RotateCcw, MoveHorizontal, Trophy, Mountain, Flag, MousePointer2, Keyboard, Home } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Slider } from '@/components/ui/slider';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Switch } from '@/components/ui/switch';
import { HEROES, WEAPONS, EQUIPMENT, MAPS, createGame, trajectory, applyShot, moveActor, useItem, aiAim, WIDTH, HEIGHT, type GameState, type Mode, type MapId, type Shot, type Skill } from '@/lib/game';
import BattleCanvas from './battle-canvas';

export const asset = (name: string) => `./assets/${name.replace(/\.png$/, '.webp')}`;
type Save = { hero: number; weapon: number; equipment: number; coins: number; wins: number; games: number; xp: number; sound: boolean; };
const defaults: Save = { hero: 0, weapon: 0, equipment: 0, coins: 1200, wins: 0, games: 0, xp: 0, sound: true };
function readSave(): Save {
  try {
    const s = JSON.parse(localStorage.getItem('ddqt-save-v1') || '{}'), saved = { ...defaults };
    for (const key of ['hero', 'weapon', 'equipment'] as const) if (Number.isInteger(s[key]) && s[key] >= 0 && s[key] < 3) saved[key] = s[key];
    for (const key of ['coins', 'wins', 'games', 'xp'] as const) if (Number.isFinite(s[key]) && s[key] >= 0) saved[key] = Math.floor(s[key]);
    if (typeof s.sound === 'boolean') saved.sound = s.sound;
    return saved;
  } catch { return { ...defaults }; }
}
function HeroArt({ hero, className = '' }: { hero: number; className?: string }) { return <img src={asset(`hero-${hero}.png`)} alt={`${HEROES[hero].name}角色立绘`} className={`hero-art ${className}`} draggable={false}/>; }
function ItemArt({ item, className = '' }: { item: number; className?: string }) { return <img src={asset(`item-${item}.png`)} alt={item < 3 ? WEAPONS[item].name : EQUIPMENT[item - 3].name} className={`item-art ${className}`} draggable={false}/>; }

export default function GameApp() {
  const [save, setSave] = useState<Save>(defaults), [loaded, setLoaded] = useState(false);
  const [screen, setScreen] = useState<'lobby' | 'battle'>('lobby');
  const [modal, setModal] = useState<'heroes' | 'weapons' | 'equipment' | 'help' | 'settings' | 'quit' | null>(null);
  const [mode, setMode] = useState<Mode>('adventure'), [map, setMap] = useState<MapId>('islands');
  const [game, setGame] = useState<GameState | null>(null), [toast, setToast] = useState('');
  const [angle, setAngle] = useState(45), [power, setPower] = useState(65), [guide, setGuide] = useState(true);
  const [skill, setSkill] = useState<Skill>('normal'), [charging, setCharging] = useState(false), [shot, setShot] = useState<Shot | null>(null);
  const [effect, setEffect] = useState<{ x: number; y: number; tick: number } | null>(null), [shotProgress, setShotProgress] = useState(0);
  const [handoff, setHandoff] = useState(false), [storageBlocked, setStorageBlocked] = useState(false);
  const gameRef = useRef(game); gameRef.current = game;
  const firing = useRef(false), audioRef = useRef<AudioContext | null>(null), chargedRef = useRef(65), rewardApplied = useRef(false);
  const currentHero = HEROES[save.hero], currentWeapon = WEAPONS[save.weapon], selectedMap = MAPS.find(m => m.id === map)!;
  const humanTurn = !!game && (game.mode !== 'adventure' || game.active === 0);
  const canAct = !!game && game.phase === 'aim' && humanTurn && !modal && !handoff;
  useEffect(() => { if (!canAct) setCharging(false); }, [canAct]);
  useEffect(() => { setSave(readSave()); setLoaded(true); }, []);
  useEffect(() => { if (loaded) try { localStorage.setItem('ddqt-save-v1', JSON.stringify(save)); } catch { setStorageBlocked(true); } }, [save, loaded]);
  useEffect(() => { if (toast) { const t = setTimeout(() => setToast(''), 3000); return () => clearTimeout(t); } }, [toast]);
  const sound = useCallback((type: 'click' | 'fire' | 'hit' | 'win') => {
    if (!save.sound) return;
    try {
      const ctx = audioRef.current || (audioRef.current = new AudioContext()); void ctx.resume();
      const notes = type === 'win' ? [523, 659, 784, 1046] : type === 'fire' ? [360, 160] : type === 'hit' ? [90, 45] : [660];
      notes.forEach((freq, i) => { const o = ctx.createOscillator(), g = ctx.createGain(); o.type = type === 'hit' ? 'triangle' : 'sine'; o.frequency.setValueAtTime(freq, ctx.currentTime + i * 0.09); g.gain.setValueAtTime(0, ctx.currentTime); g.gain.setValueAtTime(0.09, ctx.currentTime + i * 0.09); g.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + i * 0.09 + 0.22); o.connect(g); g.connect(ctx.destination); o.start(ctx.currentTime + i * 0.09); o.stop(ctx.currentTime + i * 0.09 + 0.23); });
    } catch { /* Browsers may disable sound. */ }
  }, [save.sound]);
  function choose(key: 'hero' | 'weapon' | 'equipment', value: number) { setSave(s => ({ ...s, [key]: value })); sound('click'); setToast(`已${key === 'hero' ? '出战' : '装备'}：${key === 'hero' ? HEROES[value].name : key === 'weapon' ? WEAPONS[value].name : EQUIPMENT[value].name}`); }
  function startBattle() {
    const g = createGame(mode, map, save.hero, save.weapon, save.equipment); setGame(g); gameRef.current = g; setScreen('battle'); setAngle(45); setPower(65); chargedRef.current = 65;
    setShot(null); setEffect(null); setSkill('normal'); setHandoff(false); setModal(null); setCharging(false); firing.current = false; rewardApplied.current = false; sound('click');
  }
  const launch = useCallback((a?: number, p?: number) => {
    const g = gameRef.current; if (!g || g.phase !== 'aim' || firing.current) return;
    firing.current = true;
    const boost = (g.mode !== 'adventure' || g.active === 0) && skill === 'boost' && g.energy >= 25;
    const s = trajectory(g, a ?? angle, p ?? power, boost ? 'boost' : 'normal'), next = { ...g, phase: 'flying' as const, energy: g.energy - (boost ? 25 : 0) };
    gameRef.current = next; setGame(next); setShot(s); setShotProgress(0); setCharging(false); sound('fire');
  }, [angle, power, skill, sound]);
  useEffect(() => {
    if (!shot) return;
    let frame = 0, start: number | null = null;
    const duration = Math.max(700, shot.points.length * 14);
    const animate = (time: number) => {
      if (start === null) start = time;
      const progress = Math.min(1, (time - start) / duration); setShotProgress(progress);
      if (progress < 1) frame = requestAnimationFrame(animate);
      else {
        const g = gameRef.current; if (!g) return;
        const next = applyShot(g, shot); setEffect({ ...shot.impact, tick: Date.now() }); sound('hit'); gameRef.current = next; setGame(next); setShot(null); setSkill('normal'); firing.current = false;
        if (next.mode === 'duel' && next.phase !== 'over') setHandoff(true);
      }
    };
    frame = requestAnimationFrame(animate); return () => cancelAnimationFrame(frame);
  }, [shot, sound]);
  useEffect(() => { if (effect) { const t = setTimeout(() => setEffect(null), 650); return () => clearTimeout(t); } }, [effect]);
  useEffect(() => {
    if (!game || game.phase !== 'aim' || game.mode !== 'adventure' || game.active !== 1 || modal) return;
    const timer = setTimeout(() => { const aim = aiAim(game); launch(aim.angle, aim.power); }, 1250); return () => clearTimeout(timer);
  }, [game, launch, modal]);
  useEffect(() => {
    if (!game || game.phase !== 'over' || rewardApplied.current) return;
    rewardApplied.current = true; const win = game.winner === 0, reward = game.mode === 'training' ? 30 : win ? 150 : 50;
    setSave(s => ({ ...s, coins: s.coins + reward, games: s.games + 1, wins: s.wins + (win ? 1 : 0), xp: s.xp + (win ? 100 : 30) })); sound('win');
  }, [game, sound]);
  useEffect(() => {
    if (!charging) return; let direction = 1;
    const timer = setInterval(() => { let next = chargedRef.current + direction * 1.6; if (next >= 100) { next = 100; direction = -1; } if (next <= 10) { next = 10; direction = 1; } chargedRef.current = next; setPower(Math.round(next)); }, 24);
    return () => clearInterval(timer);
  }, [charging]);
  const move = useCallback((d: number) => { setGame(g => { if (!g) return g; const next = moveActor(g, d); gameRef.current = next; return next; }); }, []);
  useEffect(() => {
    const down = (e: KeyboardEvent) => {
      const target = e.target as HTMLElement;
      if (!canAct || ['INPUT', 'TEXTAREA', 'SELECT'].includes(target?.tagName) || target?.getAttribute('role') === 'slider') return;
      if ([' ', 'ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight'].includes(e.key)) e.preventDefault();
      if (e.key === 'ArrowUp' || e.key.toLowerCase() === 'w') setAngle(a => Math.min(85, a + 1));
      if (e.key === 'ArrowDown' || e.key.toLowerCase() === 's') setAngle(a => Math.max(10, a - 1));
      if (e.key === 'ArrowLeft' || e.key.toLowerCase() === 'a') move(-1);
      if (e.key === 'ArrowRight' || e.key.toLowerCase() === 'd') move(1);
      if (e.key === ' ' && !e.repeat) { chargedRef.current = 10; setPower(10); setCharging(true); }
    };
    const up = (e: KeyboardEvent) => { if (e.key === ' ') { setCharging(false); if (charging && canAct) { e.preventDefault(); launch(undefined, chargedRef.current); } } };
    const blur = () => setCharging(false);
    window.addEventListener('keydown', down); window.addEventListener('keyup', up); window.addEventListener('blur', blur);
    return () => { window.removeEventListener('keydown', down); window.removeEventListener('keyup', up); window.removeEventListener('blur', blur); };
  }, [canAct, charging, launch, move]);
  function leaveBattle() { setScreen('lobby'); setGame(null); gameRef.current = null; setShot(null); firing.current = false; setModal(null); setCharging(false); }
  const nav = [{ id: null, label: '冒险大厅', icon: Compass }, { id: 'heroes', label: '角色图鉴', icon: Users }, { id: 'weapons', label: '武器工坊', icon: Crosshair }, { id: 'equipment', label: '装备背包', icon: Backpack }] as const;

  return <div className="game-app">
    <aside className="sidebar"><button className="brand-symbol" aria-label="弹弹奇旅首页" onClick={() => screen === 'battle' ? setModal('quit') : setModal(null)}><Crosshair size={31}/><i/></button><div className="side-nav">{nav.map(n => <button key={n.label} className={`side-link ${modal === n.id && screen === 'lobby' ? 'active' : ''}`} onClick={() => screen === 'battle' ? setModal('quit') : setModal(n.id)}><n.icon size={23}/><span>{n.label}</span>{n.id === 'weapons' && <i className="new-dot"/>}</button>)}</div><div className="side-bottom"><button onClick={() => setModal('help')} aria-label="玩法指南"><CircleHelp size={22}/></button><span>让快乐起飞</span><small>v1.0 · 原创冒险</small></div></aside>
    <div className="main-shell"><header className="topbar"><div className="wordmark">弹弹<span>奇旅</span><small>BOUNCE & BEYOND</small></div><div className="header-divider"/><span className="header-context">{screen === 'lobby' ? '冒险，从这里开始' : '天空竞技场'}</span><div className="header-right"><div className="currency"><span className="coin-icon"><Coins size={17}/></span><b>{save.coins.toLocaleString()}</b></div><div className="level-pill"><Star size={16} fill="currentColor"/><b>Lv. {Math.floor(save.xp / 300) + 1}</b></div><div className="header-divider"/><button className="icon-btn sound-button" aria-label={save.sound ? '关闭音效' : '开启音效'} onClick={() => setSave(s => ({ ...s, sound: !s.sound }))}>{save.sound ? <Volume2 size={20}/> : <VolumeX size={20}/>}</button><button className="icon-btn" aria-label="游戏设置" onClick={() => setModal('settings')}><Settings2 size={20}/></button><button className="profile-avatar" aria-label="选择出战角色" disabled={screen === 'battle'} onClick={() => setModal('heroes')}><HeroArt hero={save.hero}/></button></div></header>
    {screen === 'lobby' ? <main className="lobby"><div className="welcome-row"><div><div className="eyebrow"><span/>天空冒险季 <i/> SEASON 01</div><h1>今天，也来一场漂亮的抛物线！<Sparkles size={25}/></h1></div><button className="text-button" onClick={() => setModal('help')}>第一次冒险？<span>查看指南 <ArrowUpRight size={16}/></span></button></div>
      <div className="lobby-grid"><section className={`island-stage map-${map}`}><div className="stage-backdrop" style={{ backgroundImage: `url("${asset('islands.png')}")` }}/><div className="stage-wash"/><div className="map-label"><span className="map-badge"><span/>自由探索</span><h2>{selectedMap.name}</h2><p>{selectedMap.en}</p><div className="weather"><Wind size={16}/>{selectedMap.label}<span>24°</span></div></div><div className="stage-corner"><Mountain size={15}/>天空群岛 · 01</div><div className="hero-speech">{save.hero === 0 ? '风刚刚好，我们出发吧！' : save.hero === 1 ? '准备好，追上那颗星了吗？' : '今天也会有好事发生～'}<span>✦</span></div><div className="hero-platform"/><HeroArt hero={save.hero} className="lobby-hero"/><div className="floating-stat stat-heart"><Heart size={17} fill="currentColor"/><span>元气满格</span></div><div className="floating-stat stat-star"><Star size={17} fill="currentColor"/><span>准备就绪</span></div><button className="stage-equip equip-one" onClick={() => setModal('weapons')} aria-label="更换武器"><ItemArt item={save.weapon}/><span><Crosshair size={12}/></span></button><button className="stage-equip equip-two" onClick={() => setModal('equipment')} aria-label="更换装备"><ItemArt item={save.equipment + 3}/><span><Shield size={12}/></span></button><div className="hero-caption"><span className="hero-tier">SR</span><div><b>{currentHero.name}</b><span>{currentHero.title}</span></div><button onClick={() => setModal('heroes')} aria-label="切换角色"><RotateCcw size={18}/></button></div><div className="map-switcher">{MAPS.map((m, i) => <button key={m.id} className={map === m.id ? 'selected' : ''} onClick={() => { setMap(m.id); sound('click'); }}><span className={`map-thumb map-thumb-${i}`} style={{ backgroundImage: `url("${asset('islands.png')}")` }}/><span>{m.name}</span>{map === m.id && <Check size={13}/>}</button>)}</div></section>
      <aside className="preparation"><div className="panel-heading"><h2>出发准备</h2><span className="ready-indicator"><i/>准备就绪</span></div><div className="loadout-summary"><span className="small-label">当前出战</span><button onClick={() => setModal('heroes')}>更换 <ChevronRight size={14}/></button><div className="loadout-hero"><div className="avatar-box"><HeroArt hero={save.hero}/></div><div><h3>{currentHero.name}<span>Lv. {Math.floor(save.xp / 300) + 1}</span></h3><p>{currentHero.title}</p><span className="trait"><Sparkles size={12}/>{currentHero.trait}</span></div></div><div className="hero-metrics"><span><Heart size={14}/>生命 <b>{currentHero.hp + (save.equipment === 1 ? 20 : 0)}</b></span><span><Swords size={14}/>攻击 <b>{Math.round(currentWeapon.damage * currentHero.attack * (save.equipment === 0 ? 1.08 : 1))}</b></span></div></div><div className="weapon-select"><div className="subheading"><h3>带上趁手的武器</h3><button onClick={() => setModal('weapons')} aria-label="查看武器详情"><ArrowUpRight size={17}/></button></div><div className="weapon-mini-grid">{WEAPONS.map((w, i) => <button key={w.name} className={save.weapon === i ? 'selected' : ''} onClick={() => choose('weapon', i)}><ItemArt item={i}/><span>{w.name}</span>{save.weapon === i && <i><Check size={10}/></i>}</button>)}</div><div className="selected-weapon-info"><span>{currentWeapon.tag}</span><p>{currentWeapon.subtitle}</p></div></div><div className="mode-section"><h3>选择你的冒险</h3><div className="mode-options">{([{ id: 'adventure', title: '冒险对战', desc: '挑战 AI · 赢取星币', icon: Swords }, { id: 'training', title: '练习靶场', desc: '零风力 · 自由练习', icon: Target }, { id: 'duel', title: '同屏双人', desc: '和朋友轮流来一发', icon: Users }] as const).map(m => <button className={mode === m.id ? 'selected' : ''} key={m.id} onClick={() => { setMode(m.id); sound('click'); }}><span className="mode-icon"><m.icon size={19}/></span><span><b>{m.title}</b><small>{m.desc}</small></span><i>{mode === m.id && <span/>}</i></button>)}</div></div><button className="launch-button" disabled={!loaded} onClick={startBattle}><Swords size={23}/><span>开始冒险<small>{mode === 'adventure' ? '与 AI 一决高下' : mode === 'training' ? '找到你的完美弹道' : '两个人，双倍快乐'}</small></span><ArrowRight size={22}/></button><p className="start-note"><Shield size={12}/>无需下载 · 即刻开玩</p></aside></div>
      <section className="bottom-strip"><button className="equipment-banner" onClick={() => setModal('equipment')}><div className="banner-icon"><Backpack size={23}/></div><div><h3>小装备，大能量</h3><p>搭配你的专属冒险风格</p></div><div className="banner-equipment"><ItemArt item={3}/><ItemArt item={4}/><ItemArt item={5}/></div><ArrowUpRight size={20}/></button><div className="adventure-record"><div className="record-icon"><Trophy size={23}/></div><div><h3>我的冒险足迹</h3><p>每一次出发，都值得记录</p></div><div className="record-stat"><b>{save.games}</b><span>累计场次</span></div><div className="record-stat"><b>{save.wins}</b><span>获得胜利</span></div></div></section><footer className="lobby-footer"><span><i className="online-dot"/>冒险家，欢迎来到天空群岛</span><span>{storageBlocked ? '本次进度仅在当前页面保留' : '进度自动保存在此浏览器'}<i className="footer-dot"/>原创弹射游戏</span></footer>
    </main> : game && <main className="battle-page"><div className="battle-heading"><button className="text-button" onClick={() => setModal('quit')}><ChevronLeft size={18}/>返回大厅</button><div><span>{MAPS.find(m => m.id === game.map)?.name}</span><b>{game.mode === 'adventure' ? '冒险对战 · AI' : game.mode === 'training' ? '练习靶场' : '同屏双人'}</b></div><button className="text-button" onClick={() => setModal('help')}><CircleHelp size={17}/>玩法指南</button></div>
      <section className={`battle-arena map-${game.map}`}><div className="battle-background" style={{ backgroundImage: `url("${asset('islands.png')}")` }}/><div className="battle-sky-wash"/><div className="combat-hud">{game.actors.map((a, i) => <div className={`fighter-status fighter-${i} ${game.active === i ? 'is-active' : ''}`} key={i}><div className="fighter-avatar"><HeroArt hero={a.hero}/></div><div className="fighter-info"><div><b>{HEROES[a.hero].name}</b><span>{i === 0 ? 'P1 · 你' : game.mode === 'duel' ? 'P2 · 好友' : game.mode === 'training' ? '练习目标' : 'AI · 对手'}</span></div><div className="health-track"><span style={{ width: `${a.hp / a.maxHp * 100}%` }}/></div><div className="hp-numbers"><span><Heart size={11}/>{a.hp} / {a.maxHp}</span>{a.shield > 0 && <span><Shield size={11}/>{a.shield}</span>}</div></div></div>)}<div className="turn-indicator"><span>ROUND</span><b>{String(game.round).padStart(2, '0')}</b><div><Wind size={16}/>{game.wind === 0 ? '无风' : `${game.wind < 0 ? '←' : '→'} ${Math.abs(game.wind).toFixed(1)}`}</div></div></div>
      <BattleCanvas game={game} shot={shot} shotProgress={shotProgress} angle={angle} power={power} guide={guide && humanTurn} effect={effect} onAim={a => canAct && setAngle(a)}/>
      {game.actors.map((a, i) => <div key={i} className={`battle-character ${game.active === i && game.phase === 'aim' ? 'active-character' : ''} ${a.hp === 0 ? 'defeated' : ''}`} style={{ left: `${a.x / WIDTH * 100}%`, top: `${(a.y + 28) / HEIGHT * 100}%`, transform: `translate(-50%,-100%) ${i === 1 ? 'scaleX(-1)' : ''}` }}><HeroArt hero={a.hero}/>{a.shield > 0 && <span className="shield-bubble"/>}</div>)}<div className="battle-turn-label">{game.phase === 'flying' ? '弹弹飞行中…' : game.phase === 'over' ? game.message : game.active === 1 && game.mode === 'adventure' ? '对手正在瞄准…' : `${game.mode === 'duel' ? `P${game.active + 1}` : '轮到你了'} · 瞄准，出发！`}</div><button className={`guide-toggle ${guide ? 'on' : ''}`} onClick={() => setGuide(!guide)}><Crosshair size={15}/>{guide ? '轨迹辅助已开' : '轨迹辅助已关'}</button>{handoff && <div className="arena-overlay"><div className="handoff-card"><Users size={32}/><h2>轮到 P{game.active + 1} 了</h2><p>把操作交给{HEROES[game.actors[game.active].hero].name}的冒险家</p><button className="primary-button" onClick={() => { setHandoff(false); setAngle(45); setPower(65); }}>准备好了 <ArrowRight size={18}/></button></div></div>}</section>
      <div className="battle-message" role="status"><Sparkles size={16}/>{game.message}<span><MoveHorizontal size={14}/>移动与道具共用体力</span></div><div className="battle-controls"><div className="movement-controls"><span className="control-label">灵活走位 <small>A / D</small></span><div><button disabled={!canAct || game.energy < 5} onClick={() => move(-1)} aria-label="向左移动"><ArrowLeft size={21}/></button><button disabled={!canAct || game.energy < 5} onClick={() => move(1)} aria-label="向右移动"><ArrowRight size={21}/></button></div><span className="energy-caption"><Zap size={12}/>{game.energy} / 60 体力</span></div><div className="aim-controls"><div className="slider-label"><span>发射角度 <small>W / S</small></span><b>{angle}°</b></div><Slider aria-label="发射角度" min={10} max={85} value={[angle]} onValueChange={v => setAngle(Array.isArray(v) ? v[0] : v)} disabled={!canAct}/><div className="slider-scale"><span>10°</span><span>45°</span><span>85°</span></div></div><div className="power-controls"><div className="slider-label"><span>发射力度 <small>长按空格蓄力</small></span><b>{Math.round(power)}<small>%</small></b></div><Slider aria-label="发射力度" min={10} max={100} value={[power]} onValueChange={v => { const p = Array.isArray(v) ? v[0] : v; setPower(p); chargedRef.current = p; }} disabled={!canAct}/><div className="slider-scale"><span>轻轻一发</span><span>全力出击</span></div></div><div className="skill-controls"><button className={skill === 'boost' ? 'selected' : ''} disabled={!canAct || game.energy < 25} onClick={() => setSkill(s => s === 'boost' ? 'normal' : 'boost')} title="消耗25体力，本次伤害增加50%"><Flame size={22}/><span>强力弹</span><small>25 体力</small></button><button disabled={!canAct || game.energy < 25 || game.actors[game.active].heals === 0 || game.actors[game.active].hp === game.actors[game.active].maxHp} onClick={() => { setGame(g => g && useItem(g, 'heal')); setSkill('normal'); sound('click'); }} title="恢复35生命，消耗25体力"><Heart size={22}/><span>治疗</span><small>余 {game.actors[game.active].heals} 次</small></button><button disabled={!canAct || game.energy < 25 || game.actors[game.active].guards === 0} onClick={() => { setGame(g => g && useItem(g, 'shield')); setSkill('normal'); sound('click'); }} title="获得30护盾，消耗25体力"><Shield size={22}/><span>护盾</span><small>余 {game.actors[game.active].guards} 次</small></button></div><button className={`fire-button ${charging ? 'charging' : ''}`} disabled={!canAct} onClick={() => launch()}><Crosshair size={25}/><b>{charging ? '蓄力中' : game.phase === 'flying' ? '飞行中' : !humanTurn ? '等待对手' : '发射！'}</b><span>{skill === 'boost' ? '强力弹 · 150% 伤害' : '点击发射 / 空格蓄力'}</span></button></div><div className="battle-footer"><span><MousePointer2 size={14}/>点击战场可调整角度 · 使用滑杆精确瞄准</span><span>清空对手生命即可获胜 · 爆炸会改变地形</span></div></main>}
    </div>
    <Dialog open={modal !== null && modal !== 'quit'} onOpenChange={open => !open && setModal(null)}><DialogContent className={`game-dialog ${modal === 'help' ? 'help-dialog' : ''}`}><DialogTitle className="dialog-title">{modal === 'heroes' ? '遇见你的冒险搭档' : modal === 'weapons' ? '武器工坊' : modal === 'equipment' ? '冒险装备箱' : modal === 'settings' ? '让冒险更合心意' : '第一发，从这里开始'}</DialogTitle><DialogDescription className="dialog-description">{modal === 'heroes' ? '三位伙伴，三种天赋。选择一位，一起奔向天空。' : modal === 'weapons' ? '每件武器都有自己的脾气，找到适合你的那一款。' : modal === 'equipment' ? '每次出战可携带一件装备，效果将在下一场战斗生效。' : modal === 'settings' ? '调整音效和瞄准辅助，找到舒服的游戏节奏。' : '观察风向，调整角度和力度，将炮弹送到对手身边。'}</DialogDescription>
    {modal === 'heroes' && <div className="hero-selection-grid">{HEROES.map((h, i) => <button key={h.name} className={`hero-choice ${save.hero === i ? 'selected' : ''}`} onClick={() => choose('hero', i)} style={{ '--hero-accent': h.color } as CSSProperties}><span className="choice-rarity">SR</span><HeroArt hero={i}/><div className="hero-choice-info"><small>{h.title}</small><h3>{h.name}</h3><p>{h.text}</p><span><Sparkles size={13}/>{h.detail}</span><b className="choice-action">{save.hero === i ? <><Check size={16}/>已出战</> : '选择出战'}</b></div></button>)}</div>}
    {modal === 'weapons' && <div className="weapon-selection-grid">{WEAPONS.map((w, i) => <button key={w.name} className={`weapon-choice ${save.weapon === i ? 'selected' : ''}`} onClick={() => choose('weapon', i)}><span className="weapon-tag">{w.tag}</span><ItemArt item={i}/><h3>{w.name}</h3><p>{w.desc}</p><div className="weapon-meter"><span>伤害 <b>{w.damage}</b></span><i><em style={{ width: `${w.damage / 50 * 100}%` }}/></i></div><div className="weapon-meter"><span>范围 <b>{w.radius}</b></span><i><em style={{ width: `${w.radius}%` }}/></i></div><b className="choice-action">{save.weapon === i ? <><Check size={16}/>已装备</> : '装备武器'}</b></button>)}</div>}
    {modal === 'equipment' && <div className="equipment-selection">{EQUIPMENT.map((e, i) => <button key={e.name} className={`equipment-choice ${save.equipment === i ? 'selected' : ''}`} onClick={() => choose('equipment', i)}><ItemArt item={i + 3}/><div><span className="weapon-tag">{e.tag}</span><h3>{e.name}</h3><p>{e.desc}</p></div><span className="choice-action">{save.equipment === i ? <><Check size={16}/>已装备</> : '装备'}</span></button>)}<p className="equipment-tip"><Sparkles size={16}/>角色、武器与装备均已解锁，自由搭配，快乐出发。</p></div>}
    {modal === 'help' && <Tabs defaultValue="basics"><TabsList className="help-tabs"><TabsTrigger value="basics">快速上手</TabsTrigger><TabsTrigger value="tactics">战术小课堂</TabsTrigger></TabsList><TabsContent value="basics"><div className="help-steps"><div><span>01</span><div><h3>看一眼风，选一个角度</h3><p>上方箭头表示风向。点击战场或拖动角度滑杆，白色虚线显示预计轨迹。</p></div></div><div><span>02</span><div><h3>给炮弹刚刚好的力量</h3><p>拖动力度滑杆后点击发射。也可以长按空格蓄力，松开即发射。力度越大，飞得越远。</p></div></div><div><span>03</span><div><h3>轮流出招，直到胜利</h3><p>将对手生命降到 0 即可获胜。训练目标不会反击；同屏双人轮流操作。</p></div></div></div><div className="keyboard-guide"><Keyboard size={22}/><span><kbd>A</kbd><kbd>D</kbd>移动</span><span><kbd>W</kbd><kbd>S</kbd>角度</span><span><kbd>空格</kbd>蓄力</span></div></TabsContent><TabsContent value="tactics"><div className="tactic-list"><p><Wind/>顺风飞得更远，逆风需要更大力度。每回合风力都会变化。</p><p><Mountain/>爆炸会挖出弹坑。地形变化后，你与对手的高度也会变化。</p><p><Flame/>强力弹增加 50% 伤害，消耗 25 体力；每步移动消耗 5 体力。</p><p><Shield/>治疗与护盾各有 2 次，均消耗 25 体力。护盾优先抵挡伤害。</p><p><Target/>冰晶命中可减缓对手行动；向日葵擅长范围轰炸。</p><p><Flag/>对战上限为 60 回合，之后按剩余生命判定胜负。</p></div></TabsContent></Tabs>}
    {modal === 'settings' && <div className="settings-list"><label><div><b>游戏音效</b><p>发射、命中与胜利时的声音反馈</p></div><Switch aria-label="游戏音效" checked={save.sound} onCheckedChange={checked => setSave(s => ({ ...s, sound: checked }))}/></label><label><div><b>轨迹辅助</b><p>显示炮弹的预计飞行路线</p></div><Switch aria-label="轨迹辅助" checked={guide} onCheckedChange={setGuide}/></label><div className="save-info"><Shield size={21}/><p>{storageBlocked ? '当前浏览器无法保存进度，关闭页面后进度会丢失。' : '冒险进度保存在当前浏览器，无需注册账号。清除浏览器数据会重置进度。'}</p></div></div>}
    </DialogContent></Dialog>
    <Dialog open={modal === 'quit'} onOpenChange={open => !open && setModal(null)}><DialogContent className="small-dialog"><DialogTitle>暂时返回天空群岛？</DialogTitle><DialogDescription>本场对战将结束，未完成的对战不会获得奖励。</DialogDescription><div className="dialog-buttons"><button className="secondary-button" onClick={() => setModal(null)}>继续对战</button><button className="primary-button" onClick={leaveBattle}>返回大厅</button></div></DialogContent></Dialog>
    <Dialog open={game?.phase === 'over' && screen === 'battle'}><DialogContent className="result-dialog" showCloseButton={false}><div className="result-trophy"><Trophy size={55}/></div><span className="eyebrow">ADVENTURE COMPLETE</span><DialogTitle>{game?.winner === null ? '这一次，旗鼓相当！' : game?.mode === 'duel' ? `P${game.winner! + 1}，漂亮的一发！` : game?.winner === 0 ? '胜利！天空为你喝彩' : '差一点！再来一场吧'}</DialogTitle><DialogDescription>{game?.mode === 'training' ? '每一发练习，都让你更靠近完美弹道。' : `在第 ${game?.round} 回合，完成了这次冒险。`}</DialogDescription><div className="result-rewards"><span><Coins size={20}/>+{game?.mode === 'training' ? 30 : game?.winner === 0 ? 150 : 50} 星币</span><span><Star size={20}/>+{game?.winner === 0 ? 100 : 30} 经验</span></div><div className="dialog-buttons"><button className="secondary-button" onClick={leaveBattle}><Home size={17}/>返回大厅</button><button className="primary-button" onClick={startBattle}><RotateCcw size={17}/>再来一场</button></div></DialogContent></Dialog>
    {toast && <div className="toast-message" role="status"><Check size={17}/>{toast}</div>}
  </div>;
}
